var express = require('express');
var router = express.Router();
const Thumbnail = require('../models/thumbnail');
const mongoose = require('mongoose');
const debug = require('debug')('geo:thumbnails');
const ObjectId = mongoose.Types.ObjectId;
const utils = require('./utils');
const Guess = require('../models/guess');


/* GET thumbnails listing. */
router.get('/', function(req, res, next) {
  Thumbnail.find().sort('created_at').exec(function(err, thumbnails) {
    if (err) {
      return next(err);
    }
    res.send(thumbnails);
  });
});

/**
 * @api {post} /api/thumbnails Create a thumbnail
 * @apiName CreateThumbnail
 * @apiGroup Thumbnail
 * @apiVersion 1.0.0
 * @apiDescription Registers a new thumbnail.
 *
 * @apiUse ThumbnailInRequestBody
 * @apiUse ThumbnailInResponseBody
 * @apiUse ThumbnailValidationError
 * @apiSuccess (Response body) {String} id A unique identifier for the thumbnail generated by the server
 *
 * @apiExample Example
 *     POST /api/thumbnails HTTP/1.1
 *     Content-Type: application/json
 *
 *     {
 *       "title": "Beautiful landscape",
 *       "location": {"type": "Point", "coordinates": [ -73.856077, 40.848447 ]},
 *       "img": "/sdcard/Images/landscape_image.jpg"
 *     }
 *
 * @apiSuccessExample 201 Created
 *     HTTP/1.1 201 Created
 *     Content-Type: application/json
 *     Location: https://comem-archioweb-2019-2020-g.herokuapp.com/api/thumbnnails/58b2926f5e1def0123e97bc0
 *
 *     {
 *       "id": "58b2926f5e1def0123e97bc0",
 *       "title": "Beautiful landscape",
 *       "location": {"type": "Point", "coordinates": [ -73.856077, 40.848447 ]},
 *       "img": "/sdcard/Images/landscape_image.jpg"
 *       "user_Id": "78b2926f5e1def0123e97bc0"
*       }
 */

/* POST new thumbnail */
router.post('/', function(req, res, next) {
  // Create a new document from the JSON in the request body
  const newThumbnail = new Thumbnail(req.body);
  // Save that document
  newThumbnail.save(function(err, savedThumbnail) {
    if (err) {
      return next(err);
    }
    // Send the saved document in the response
    res
    .status(201)
    .set('Location', `${config.baseUrl}/thumbnails/${savedThumbnail._id}`)
    .send(savedThumbnail);
  });
});



/*GET one thumbnail*/
router.get('/:id', loadThumbnailFromParamsMiddleware, function (req, res, next) {
  res.send(req.thumbnail);
});

function loadThumbnailFromParamsMiddleware(req, res, next) {

  const thumbnailId = req.params.id;
  if (!ObjectId.isValid(thumbnailId)) {
    return movieNotFound(res, thumbnailId);
  }

  let query = Thumbnail.findById(thumbnailId)

  query.exec(function (err, thumbnail) {
    if (err) {
      return next(err);
    } else if (!thumbnail) {
      return thumbnailNotFound(res, thumbnailId);
    }

    req.thumbnail = thumbnail;
    next();
  });
}

function thumbnailNotFound(res, thumbnailId) {
  return res.status(404).type('text').send(`No thumbnail found with ID ${thumbnailId}`);
}

/*DELETE thumbnail*/
router.delete('/:id', loadThumbnailFromParamsMiddleware, function (req, res, next) {



    req.thumbnail.remove(function (err) {
      if (err) {
        return next(err);
      }
//requête pour effacer les guess puis renvoyer 204
Guess.remove({ thumbnail_id:req.thumbnail._id }, function(err){
    if (err) {
        return next(err);
      }
            debug(`Deleted thumbnail "${req.thumbnail.title}"`);
      res.sendStatus(204);
})
//Character.remove({ name: 'Eddard Stark' }, function)

    });
        });


/*PATCH thumbnail*/
router.patch('/:id', utils.requireJson, loadThumbnailFromParamsMiddleware, function (req, res, next) {

  // Update only properties present in the request body
  if (req.body.title !== undefined) {
    req.thumbnail.title = req.body.title;
  }



  req.thumbnail.save(function (err, savedThumbnail) {
    if (err) {
      return next(err);
    }

    debug(`Updated thumbnail "${savedThumbnail.title}"`);
    res.send(savedThumbnail);
  });
});

module.exports = router;